---
# tasks file for roles/rust
- name: Install Rust toolchain packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - rust
      - cargo
      - rustfmt
      - clippy

